Demo/ManagerSide/ManagerSide/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ManagerSide.Models;

namespace ManagerSide.Controllers
{
    public class IndexController : Controller
    {
        private Entities db = new Entities();

        [Authorize]
        // GET: Index/Index
        public ActionResult Index()
        {
            CommonModel modelForIndex = new CommonModel();
            var maleUser = db.Users.Where(u => u.gender.Equals("Nam") && u.typeID == 3).ToList();
            var femaleUser = db.Users.Where(u => u.gender.Equals("Nữ") && u.typeID == 3).ToList();
            var allUser = db.Users.Where(u => u.typeID == 3).ToList();
            var maleProduct = db.Products.OrderByDescending(p => p.productRate).ToList();
            modelForIndex.maleUser = maleUser.Count();
            modelForIndex.femaleUser = femaleUser.Count();
            modelForIndex.otherUser = allUser.Count() - maleUser.Count() - femaleUser.Count();

            //for (int i = 0; i < maleProduct.Count(); i++)
            //{
            //    if (i == 0)
            //    {
            //        ProductSold<int, string> product = new ProductSold<int, string>();
            //        product.Amount = maleProduct.ElementAt(i).productRate;
            //        product.Key = maleProduct.ElementAt(i).productName;
            //        modelForIndex.top1RateProduct = product;
            //    }
            //    if (i == 1)
            //    {
            //        ProductSold<int, string> product = new ProductSold<int, string>();
            //        product.Amount = maleProduct.ElementAt(i).productRate;
            //        product.Key = maleProduct.ElementAt(i).productName;
            //        modelForIndex.top2RateProduct = product;
            //    }
            //    if (i == 2)
            //    {
            //        ProductSold<int, string> product = new ProductSold<int, string>();
            //        product.Amount = maleProduct.ElementAt(i).productRate;
            //        product.Key = maleProduct.ElementAt(i).productName;
            //        modelForIndex.top3RateProduct = product;
            //    }
            //}
            modelForIndex.revenue = getRevenue();

            return View(modelForIndex);
        }

        public List<MonthlyRevenue> getRevenue()
        {
            List<MonthlyRevenue> revenue = new List<MonthlyRevenue>();
            double revenue1 = 0, revenue2 = 0, revenue3 = 0, revenue4 = 0, revenue5 = 0, revenue6 = 0, revenue7 = 0, revenue8 = 0, revenue9 = 0, revenue10 = 0, revenue11 = 0, revenue12 = 0;
            IEnumerable<OrderDetail> orderDetails = db.OrderDetails.Where(od => od.Order.orderStatus.Equals("Đã xử lý")).ToList();
            
            for (int i = 0; i < orderDetails.Count(); i++)
            {
                string productID = orderDetails.ElementAt(i).productID;
                DateTime dateCreate = DateTime.Parse(orderDetails.ElementAt(i).Order.dateCreate);
                IEnumerable<ImportShipment> importProduct = db.ImportShipments.Where(q => q.productID.Equals(productID)).ToList();
                if (dateCreate.Year == 2020)
                {
                    for (int x = 0; x < importProduct.Count(); x++)
                    {
                        if (dateCreate.Month < importProduct.ElementAt(x).importDate.Value.Month && dateCreate.Year == importProduct.ElementAt(x).importDate.Value.Year)
                        {
                            double monthRevenue = (orderDetails.ElementAt(i).productTotalPrice - importProduct.ElementAt(x - 1).importPrice) * orderDetails.ElementAt(i).productQuantityOrder;
                            double price = importProduct.ElementAt(x - 1).importPrice;
                            switch (dateCreate.Month)
                            {
                                case 1:
                                    {
                                        revenue1 += monthRevenue;
                                        break;
                                    }
                                case 2:
                                    {
                                        revenue2 += monthRevenue;
                                        break;
                                    }
                                case 3:
                                    {
                                        revenue3 += monthRevenue;
                                        break;
                                    }
                                case 4:
                                    {
                                        revenue4 += monthRevenue;
                                        break;
                                    }
                                case 5:
                                    {
                                        revenue5 += monthRevenue;
                                        break;
                                    }
                                case 6:
                                    {
                                        revenue6 += monthRevenue;
                                        break;
                                    }
                                case 7:
                                    {
                                        revenue7 += monthRevenue;
                                        break;
                                    }
                                case 8:
                                    {
                                        revenue8 += monthRevenue;
                                        break;
                                    }
                                case 9:
                                    {
                                        revenue9 += monthRevenue;
                                        break;
                                    }
                                case 10:
                                    {
                                        revenue10 += monthRevenue;
                                        break;
                                    }
                                case 11:
                                    {
                                        revenue11 += monthRevenue;
                                        break;
                                    }
                                case 12:
                                    {
                                        revenue12 += monthRevenue;
                                        break;
                                    }
                                default:
                                    {
                                        break;
                                    }
                            }
                        }
                        if (dateCreate.Month == importProduct.ElementAt(x).importDate.Value.Month && dateCreate.Year == importProduct.ElementAt(x).importDate.Value.Year)
                        {
                            double monthRevenue = (orderDetails.ElementAt(i).productTotalPrice - importProduct.ElementAt(x).importPrice) * orderDetails.ElementAt(i).productQuantityOrder;
                            switch (dateCreate.Month)
                            {
                                case 1:
                                    {
                                        revenue1 += monthRevenue;
                                        break;
                                    }
                                case 2:
                                    {
                                        revenue2 += monthRevenue;
                                        break;
                                    }
                                case 3:
                                    {
                                        revenue3 += monthRevenue;
                                        break;
                                    }
                                case 4:
                                    {
                                        revenue4 += monthRevenue;
                                        break;
                                    }
                                case 5:
                                    {
                                        revenue5 += monthRevenue;
                                        break;
                                    }
                                case 6:
                                    {
                                        revenue6 += monthRevenue;
                                        break;
                                    }
                                case 7:
                                    {
                                        revenue7 += monthRevenue;
                                        break;
                                    }
                                case 8:
                                    {
                                        revenue8 += monthRevenue;
                                        break;
                                    }
                                case 9:
                                    {
                                        revenue9 += monthRevenue;
                                        break;
                                    }
                                case 10:
                                    {
                                        revenue10 += monthRevenue;
                                        break;
                                    }
                                case 11:
                                    {
                                        revenue11 += monthRevenue;
                                        break;
                                    }
                                case 12:
                                    {

Demo/ManagerSide/ManagerSide/Views/CommonLayout/_Layout.cshtml
@{ 
    Layout = null;
    int role = Convert.ToInt32(Session["role"]);
    string fullname = Session["user"].ToString();
    //string image = Session["image"].ToString();
    string id = Session["id"].ToString();
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Layout</title>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- CSS file from w3school -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/Css_Management/TopBarandSideBar.css">
    <link rel="stylesheet" type="text/css" href="/Css_Management/BodyandFont.css">
</head>
<body>
    <style>
        .AccountInfor{
            input[type=button]{                
                                  background-color: var(--red);
                                  border: none;
                                  color: white;
                                  text-align: center;
                                  display: inline-block;
                                  cursor: pointer;
                              } 
        }
    </style>
    @Html.Raw(ViewBag.Message)

    <div class="SideBar">
        <img src="~/Img/Logo.png" />
        <a href="~/Index/Index">Trang chủ</a>
        <a href="~/Users/Index">Quản lý người dùng</a>
        <a href="~/Products/Index">Quản lý sản phẩm</a>
        <a href="~/Orders/Index">Quản lý đơn hàng</a>
        <a href="~/Suppliers/Index">Quản lý nhà cung cấp</a>
        <a href="~/Inventories/Index">Quản lý nhà kho</a>
    </div>
    <div class="TopBar">
        @using (Html.BeginForm("Search", "Index", FormMethod.Get))
        {
            <input type="text" placeholder="Tìm kiếm.." name="search" id="myInput">
        }
        <div class="AccountInfor" style="text-transform:capitalize;" >
            @*<img id="avatar" src="~/Images/@image" style="width:30px; height:30px" />*@
            <ul style="list-style: none;">
                <li><a href="~/Index/EditProfile/@id">@fullname</a></li>
                <li><input type="button" value="Đăng xuất" id="logout" onclick="logout()" 
                           style="background-color: var(--red);
                                  border: none;
                                  color: white;
                                  text-align: center;
                                  display: inline-block;
                                  cursor: pointer;
                                  margin-left: 14px;"/></li>
            </ul>
        </div>
    </div>
    @RenderBody()
    <script>
        // Get the input field
        var input = document.getElementById("myInput");

        // Execute a function when the user releases a key on the keyboard
        input.addEventListener("keyup", function(event) {
        // Number 13 is the "Enter" key on the keyboard
        if (event.keyCode === 13) {
        // Cancel the default action, if needed
        event.preventDefault();
        }
        });
        $("#myInput").autocomplete({
        source: function (request, response) {
            $.ajax({
                url: '@Url.Action("GetSearchValue","Products")',
                dataType: "json",
                data: { search: $("#myInput").val() },
                success: function (data) {
                    response($.map(data, function (item) {
                        return { label: item, value: item };
                    }));
                },
                error: function (xhr, status, error) {
                    alert("Error");
                }
            });
        }
        });
        function logout() {
            $.ajax({
                type: 'POST',
                url: '/Login/Logout',
                data: { },
                success: function (data) {
                    alert("Logout thành công");
                    window.location.href = "../../Login/Login";
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                }
            });
        }
    </script>
</body>
</html>